/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DigitalFemsa.net.Client.OpenAPIDateConverter;

namespace DigitalFemsa.net.Model
{
    /// <summary>
    /// Company balance summary.  Monetary fields are returned as arrays of amounts grouped by currency (see &#x60;balance_common_field&#x60; items). 
    /// </summary>
    [DataContract(Name = "balance_response")]
    public partial class BalanceResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BalanceResponse" /> class.
        /// </summary>
        /// <param name="available">Amounts currently available, grouped by currency..</param>
        /// <param name="cashoutRetentionAmount">The balance&#39;s cashout retention amount.</param>
        /// <param name="conektaRetention">The balance&#39;s Femsa retention.</param>
        /// <param name="gateway">Gateway balance amounts, grouped by currency..</param>
        /// <param name="pending">Amounts pending settlement, grouped by currency..</param>
        /// <param name="retained">Amounts currently retained, grouped by currency..</param>
        /// <param name="retentionAmount">Retention amount applied, grouped by currency..</param>
        /// <param name="targetCollateralAmount">Target collateral amount, grouped by currency..</param>
        /// <param name="targetRetentionAmount">Target retention amount, grouped by currency..</param>
        /// <param name="temporarilyRetained">Amounts temporarily retained.</param>
        public BalanceResponse(List<BalanceCommonField> available = default(List<BalanceCommonField>), List<BalanceCommonField> cashoutRetentionAmount = default(List<BalanceCommonField>), List<BalanceCommonField> conektaRetention = default(List<BalanceCommonField>), List<BalanceCommonField> gateway = default(List<BalanceCommonField>), List<BalanceCommonField> pending = default(List<BalanceCommonField>), List<BalanceCommonField> retained = default(List<BalanceCommonField>), List<BalanceCommonField> retentionAmount = default(List<BalanceCommonField>), Object targetCollateralAmount = default(Object), List<BalanceCommonField> targetRetentionAmount = default(List<BalanceCommonField>), List<BalanceCommonField> temporarilyRetained = default(List<BalanceCommonField>))
        {
            this.Available = available;
            this.CashoutRetentionAmount = cashoutRetentionAmount;
            this.ConektaRetention = conektaRetention;
            this.Gateway = gateway;
            this.Pending = pending;
            this.Retained = retained;
            this.RetentionAmount = retentionAmount;
            this.TargetCollateralAmount = targetCollateralAmount;
            this.TargetRetentionAmount = targetRetentionAmount;
            this.TemporarilyRetained = temporarilyRetained;
        }

        /// <summary>
        /// Amounts currently available, grouped by currency.
        /// </summary>
        /// <value>Amounts currently available, grouped by currency.</value>
        [DataMember(Name = "available", EmitDefaultValue = false)]
        public List<BalanceCommonField> Available { get; set; }

        /// <summary>
        /// The balance&#39;s cashout retention amount
        /// </summary>
        /// <value>The balance&#39;s cashout retention amount</value>
        [DataMember(Name = "cashout_retention_amount", EmitDefaultValue = false)]
        public List<BalanceCommonField> CashoutRetentionAmount { get; set; }

        /// <summary>
        /// The balance&#39;s Femsa retention
        /// </summary>
        /// <value>The balance&#39;s Femsa retention</value>
        [DataMember(Name = "conekta_retention", EmitDefaultValue = false)]
        public List<BalanceCommonField> ConektaRetention { get; set; }

        /// <summary>
        /// Gateway balance amounts, grouped by currency.
        /// </summary>
        /// <value>Gateway balance amounts, grouped by currency.</value>
        [DataMember(Name = "gateway", EmitDefaultValue = false)]
        public List<BalanceCommonField> Gateway { get; set; }

        /// <summary>
        /// Amounts pending settlement, grouped by currency.
        /// </summary>
        /// <value>Amounts pending settlement, grouped by currency.</value>
        [DataMember(Name = "pending", EmitDefaultValue = false)]
        public List<BalanceCommonField> Pending { get; set; }

        /// <summary>
        /// Amounts currently retained, grouped by currency.
        /// </summary>
        /// <value>Amounts currently retained, grouped by currency.</value>
        [DataMember(Name = "retained", EmitDefaultValue = false)]
        public List<BalanceCommonField> Retained { get; set; }

        /// <summary>
        /// Retention amount applied, grouped by currency.
        /// </summary>
        /// <value>Retention amount applied, grouped by currency.</value>
        [DataMember(Name = "retention_amount", EmitDefaultValue = false)]
        public List<BalanceCommonField> RetentionAmount { get; set; }

        /// <summary>
        /// Target collateral amount, grouped by currency.
        /// </summary>
        /// <value>Target collateral amount, grouped by currency.</value>
        [DataMember(Name = "target_collateral_amount", EmitDefaultValue = false)]
        public Object TargetCollateralAmount { get; set; }

        /// <summary>
        /// Target retention amount, grouped by currency.
        /// </summary>
        /// <value>Target retention amount, grouped by currency.</value>
        [DataMember(Name = "target_retention_amount", EmitDefaultValue = false)]
        public List<BalanceCommonField> TargetRetentionAmount { get; set; }

        /// <summary>
        /// Amounts temporarily retained
        /// </summary>
        /// <value>Amounts temporarily retained</value>
        [DataMember(Name = "temporarily_retained", EmitDefaultValue = false)]
        public List<BalanceCommonField> TemporarilyRetained { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BalanceResponse {\n");
            sb.Append("  Available: ").Append(Available).Append("\n");
            sb.Append("  CashoutRetentionAmount: ").Append(CashoutRetentionAmount).Append("\n");
            sb.Append("  ConektaRetention: ").Append(ConektaRetention).Append("\n");
            sb.Append("  Gateway: ").Append(Gateway).Append("\n");
            sb.Append("  Pending: ").Append(Pending).Append("\n");
            sb.Append("  Retained: ").Append(Retained).Append("\n");
            sb.Append("  RetentionAmount: ").Append(RetentionAmount).Append("\n");
            sb.Append("  TargetCollateralAmount: ").Append(TargetCollateralAmount).Append("\n");
            sb.Append("  TargetRetentionAmount: ").Append(TargetRetentionAmount).Append("\n");
            sb.Append("  TemporarilyRetained: ").Append(TemporarilyRetained).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
