/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DigitalFemsa.net.Client.OpenAPIDateConverter;

namespace DigitalFemsa.net.Model
{
    /// <summary>
    /// Attributes used to create the order when a new payment is received.
    /// </summary>
    [DataContract(Name = "checkout_order_template")]
    public partial class CheckoutOrderTemplate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutOrderTemplate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CheckoutOrderTemplate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutOrderTemplate" /> class.
        /// </summary>
        /// <param name="currency">ISO 4217 currency code for the order. (required).</param>
        /// <param name="customerInfo">customerInfo.</param>
        /// <param name="lineItems">Products to buy. Each contains unit price and quantity used to calculate the order total. (required).</param>
        /// <param name="metadata">Arbitrary key-value data attached to the order for internal use..</param>
        public CheckoutOrderTemplate(string currency = default(string), CheckoutOrderTemplateCustomerInfo customerInfo = default(CheckoutOrderTemplateCustomerInfo), List<Product> lineItems = default(List<Product>), Dictionary<string, Object> metadata = default(Dictionary<string, Object>))
        {
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for CheckoutOrderTemplate and cannot be null");
            }
            this.Currency = currency;
            // to ensure "lineItems" is required (not null)
            if (lineItems == null)
            {
                throw new ArgumentNullException("lineItems is a required property for CheckoutOrderTemplate and cannot be null");
            }
            this.LineItems = lineItems;
            this.CustomerInfo = customerInfo;
            this.Metadata = metadata;
        }

        /// <summary>
        /// ISO 4217 currency code for the order.
        /// </summary>
        /// <value>ISO 4217 currency code for the order.</value>
        /// <example>MXN</example>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets CustomerInfo
        /// </summary>
        [DataMember(Name = "customer_info", EmitDefaultValue = false)]
        public CheckoutOrderTemplateCustomerInfo CustomerInfo { get; set; }

        /// <summary>
        /// Products to buy. Each contains unit price and quantity used to calculate the order total.
        /// </summary>
        /// <value>Products to buy. Each contains unit price and quantity used to calculate the order total.</value>
        [DataMember(Name = "line_items", IsRequired = true, EmitDefaultValue = true)]
        public List<Product> LineItems { get; set; }

        /// <summary>
        /// Arbitrary key-value data attached to the order for internal use.
        /// </summary>
        /// <value>Arbitrary key-value data attached to the order for internal use.</value>
        /// <example>{&quot;key&quot;:&quot;value&quot;}</example>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckoutOrderTemplate {\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  CustomerInfo: ").Append(CustomerInfo).Append("\n");
            sb.Append("  LineItems: ").Append(LineItems).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Currency (string) maxLength
            if (this.Currency != null && this.Currency.Length > 3)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Currency, length must be less than 3.", new [] { "Currency" });
            }

            yield break;
        }
    }

}
