/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DigitalFemsa.net.Client.OpenAPIDateConverter;

namespace DigitalFemsa.net.Model
{
    /// <summary>
    /// Customer create request.
    /// </summary>
    [DataContract(Name = "customer")]
    public partial class Customer : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Customer" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Customer() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Customer" /> class.
        /// </summary>
        /// <param name="name">Customer&#39;s name. (required).</param>
        /// <param name="email">Customer email address. (required).</param>
        /// <param name="phone">Customer phone number..</param>
        /// <param name="corporate">Indicates whether the customer email is corporate. (default to false).</param>
        /// <param name="customReference">Merchant-defined reference used to identify the customer in your system..</param>
        /// <param name="metadata">Arbitrary metadata associated with the customer..</param>
        /// <param name="paymentSources">Customer payment sources to be created with the customer (optional)..</param>
        /// <param name="fiscalEntities">Customer fiscal entities to be created with the customer (optional)..</param>
        /// <param name="shippingContacts">Customer shipping contacts to be created with the customer (optional)..</param>
        public Customer(string name = default(string), string email = default(string), string phone = default(string), bool corporate = false, string customReference = default(string), Dictionary<string, Object> metadata = default(Dictionary<string, Object>), List<CustomerPaymentMethodsRequest> paymentSources = default(List<CustomerPaymentMethodsRequest>), List<CustomerFiscalEntitiesRequest> fiscalEntities = default(List<CustomerFiscalEntitiesRequest>), List<CustomerShippingContacts> shippingContacts = default(List<CustomerShippingContacts>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for Customer and cannot be null");
            }
            this.Name = name;
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for Customer and cannot be null");
            }
            this.Email = email;
            this.Phone = phone;
            this.Corporate = corporate;
            this.CustomReference = customReference;
            this.Metadata = metadata;
            this.PaymentSources = paymentSources;
            this.FiscalEntities = fiscalEntities;
            this.ShippingContacts = shippingContacts;
        }

        /// <summary>
        /// Customer&#39;s name.
        /// </summary>
        /// <value>Customer&#39;s name.</value>
        /// <example>miguel</example>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Customer email address.
        /// </summary>
        /// <value>Customer email address.</value>
        /// <example>miguel@gmail.com</example>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Customer phone number.
        /// </summary>
        /// <value>Customer phone number.</value>
        /// <example>+5215555555555</example>
        [DataMember(Name = "phone", EmitDefaultValue = true)]
        public string Phone { get; set; }

        /// <summary>
        /// Indicates whether the customer email is corporate.
        /// </summary>
        /// <value>Indicates whether the customer email is corporate.</value>
        /// <example>false</example>
        [DataMember(Name = "corporate", EmitDefaultValue = true)]
        public bool Corporate { get; set; }

        /// <summary>
        /// Merchant-defined reference used to identify the customer in your system.
        /// </summary>
        /// <value>Merchant-defined reference used to identify the customer in your system.</value>
        [DataMember(Name = "custom_reference", EmitDefaultValue = false)]
        public string CustomReference { get; set; }

        /// <summary>
        /// Arbitrary metadata associated with the customer.
        /// </summary>
        /// <value>Arbitrary metadata associated with the customer.</value>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Customer payment sources to be created with the customer (optional).
        /// </summary>
        /// <value>Customer payment sources to be created with the customer (optional).</value>
        [DataMember(Name = "payment_sources", EmitDefaultValue = false)]
        public List<CustomerPaymentMethodsRequest> PaymentSources { get; set; }

        /// <summary>
        /// Customer fiscal entities to be created with the customer (optional).
        /// </summary>
        /// <value>Customer fiscal entities to be created with the customer (optional).</value>
        [DataMember(Name = "fiscal_entities", EmitDefaultValue = false)]
        public List<CustomerFiscalEntitiesRequest> FiscalEntities { get; set; }

        /// <summary>
        /// Customer shipping contacts to be created with the customer (optional).
        /// </summary>
        /// <value>Customer shipping contacts to be created with the customer (optional).</value>
        [DataMember(Name = "shipping_contacts", EmitDefaultValue = false)]
        public List<CustomerShippingContacts> ShippingContacts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Customer {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Corporate: ").Append(Corporate).Append("\n");
            sb.Append("  CustomReference: ").Append(CustomReference).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  PaymentSources: ").Append(PaymentSources).Append("\n");
            sb.Append("  FiscalEntities: ").Append(FiscalEntities).Append("\n");
            sb.Append("  ShippingContacts: ").Append(ShippingContacts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Phone (string) maxLength
            if (this.Phone != null && this.Phone.Length > 19)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Phone, length must be less than 19.", new [] { "Phone" });
            }

            yield break;
        }
    }

}
