/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DigitalFemsa.net.Client.OpenAPIDateConverter;

namespace DigitalFemsa.net.Model
{
    /// <summary>
    /// Order model. Some nested resources are returned as list previews (for example: &#x60;charges&#x60;, &#x60;line_items&#x60;), and may be &#x60;null&#x60; depending on the request/context. The &#x60;checkout&#x60; field is only present when the order is linked to a checkout (&#x60;channel.checkout_request_id&#x60;). 
    /// </summary>
    [DataContract(Name = "order_response")]
    public partial class OrderResponse : IValidatableObject
    {
        /// <summary>
        /// Defines Object
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ObjectEnum
        {
            /// <summary>
            /// Enum Order for value: order
            /// </summary>
            [EnumMember(Value = "order")]
            Order = 1
        }


        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        /// <example>order</example>
        [DataMember(Name = "object", EmitDefaultValue = false)]
        public ObjectEnum? Object { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderResponse" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="varObject">varObject.</param>
        /// <param name="livemode">livemode.</param>
        /// <param name="amount">amount.</param>
        /// <param name="currency">currency.</param>
        /// <param name="paymentStatus">Current payment status of the order. It can be &#x60;null&#x60; for orders without payment information yet..</param>
        /// <param name="amountRefunded">amountRefunded.</param>
        /// <param name="splitPayment">Indicates whether the order uses split payments (when available/configured)..</param>
        /// <param name="metadata">Metadata attached to the order..</param>
        /// <param name="isRefundable">Indicates whether the order is currently refundable..</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="updatedAt">updatedAt.</param>
        /// <param name="customerInfo">customerInfo.</param>
        /// <param name="shippingContact">shippingContact.</param>
        /// <param name="channel">channel.</param>
        /// <param name="fiscalEntity">fiscalEntity.</param>
        /// <param name="checkout">checkout.</param>
        /// <param name="lineItems">lineItems.</param>
        /// <param name="discountLines">discountLines.</param>
        /// <param name="charges">charges.</param>
        /// <param name="partialReference">Partial reference information (when applicable). Structure may vary depending on the payment flow..</param>
        /// <param name="paymentsInfo">Additional payment information (when available). Structure may vary..</param>
        public OrderResponse(string id = default(string), ObjectEnum? varObject = default(ObjectEnum?), bool livemode = default(bool), int amount = default(int), string currency = default(string), string paymentStatus = default(string), int amountRefunded = default(int), bool? splitPayment = default(bool?), Dictionary<string, Object> metadata = default(Dictionary<string, Object>), bool isRefundable = default(bool), long createdAt = default(long), long updatedAt = default(long), OrderResponseCustomerInfo customerInfo = default(OrderResponseCustomerInfo), OrderResponseShippingContact shippingContact = default(OrderResponseShippingContact), OrderResponseChannel channel = default(OrderResponseChannel), OrderFiscalEntityResponse fiscalEntity = default(OrderFiscalEntityResponse), OrderResponseCheckout checkout = default(OrderResponseCheckout), OrderResponseProducts lineItems = default(OrderResponseProducts), OrderResponseDiscountLines discountLines = default(OrderResponseDiscountLines), OrderResponseCharges charges = default(OrderResponseCharges), Dictionary<string, Object> partialReference = default(Dictionary<string, Object>), Dictionary<string, Object> paymentsInfo = default(Dictionary<string, Object>))
        {
            this.Id = id;
            this.Object = varObject;
            this.Livemode = livemode;
            this.Amount = amount;
            this.Currency = currency;
            this.PaymentStatus = paymentStatus;
            this.AmountRefunded = amountRefunded;
            this.SplitPayment = splitPayment;
            this.Metadata = metadata;
            this.IsRefundable = isRefundable;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.CustomerInfo = customerInfo;
            this.ShippingContact = shippingContact;
            this.Channel = channel;
            this.FiscalEntity = fiscalEntity;
            this.Checkout = checkout;
            this.LineItems = lineItems;
            this.DiscountLines = discountLines;
            this.Charges = charges;
            this.PartialReference = partialReference;
            this.PaymentsInfo = paymentsInfo;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /// <example>ord_2zKSF2aUY2kBRcyXJ</example>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Livemode
        /// </summary>
        /// <example>true</example>
        [DataMember(Name = "livemode", EmitDefaultValue = true)]
        public bool Livemode { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        /// <example>10000</example>
        [DataMember(Name = "amount", EmitDefaultValue = false)]
        public int Amount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        /// <example>MXN</example>
        [DataMember(Name = "currency", EmitDefaultValue = false)]
        public string Currency { get; set; }

        /// <summary>
        /// Current payment status of the order. It can be &#x60;null&#x60; for orders without payment information yet.
        /// </summary>
        /// <value>Current payment status of the order. It can be &#x60;null&#x60; for orders without payment information yet.</value>
        /// <example>pending_payment</example>
        [DataMember(Name = "payment_status", EmitDefaultValue = true)]
        public string PaymentStatus { get; set; }

        /// <summary>
        /// Gets or Sets AmountRefunded
        /// </summary>
        /// <example>0</example>
        [DataMember(Name = "amount_refunded", EmitDefaultValue = false)]
        public int AmountRefunded { get; set; }

        /// <summary>
        /// Indicates whether the order uses split payments (when available/configured).
        /// </summary>
        /// <value>Indicates whether the order uses split payments (when available/configured).</value>
        [DataMember(Name = "split_payment", EmitDefaultValue = true)]
        public bool? SplitPayment { get; set; }

        /// <summary>
        /// Metadata attached to the order.
        /// </summary>
        /// <value>Metadata attached to the order.</value>
        /// <example>{}</example>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Indicates whether the order is currently refundable.
        /// </summary>
        /// <value>Indicates whether the order is currently refundable.</value>
        /// <example>false</example>
        [DataMember(Name = "is_refundable", EmitDefaultValue = true)]
        public bool IsRefundable { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /// <example>1767651766</example>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public long CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /// <example>1767651766</example>
        [DataMember(Name = "updated_at", EmitDefaultValue = false)]
        public long UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets CustomerInfo
        /// </summary>
        [DataMember(Name = "customer_info", EmitDefaultValue = false)]
        public OrderResponseCustomerInfo CustomerInfo { get; set; }

        /// <summary>
        /// Gets or Sets ShippingContact
        /// </summary>
        [DataMember(Name = "shipping_contact", EmitDefaultValue = true)]
        public OrderResponseShippingContact ShippingContact { get; set; }

        /// <summary>
        /// Gets or Sets Channel
        /// </summary>
        [DataMember(Name = "channel", EmitDefaultValue = true)]
        public OrderResponseChannel Channel { get; set; }

        /// <summary>
        /// Gets or Sets FiscalEntity
        /// </summary>
        [DataMember(Name = "fiscal_entity", EmitDefaultValue = true)]
        public OrderFiscalEntityResponse FiscalEntity { get; set; }

        /// <summary>
        /// Gets or Sets Checkout
        /// </summary>
        [DataMember(Name = "checkout", EmitDefaultValue = false)]
        public OrderResponseCheckout Checkout { get; set; }

        /// <summary>
        /// Gets or Sets LineItems
        /// </summary>
        [DataMember(Name = "line_items", EmitDefaultValue = false)]
        public OrderResponseProducts LineItems { get; set; }

        /// <summary>
        /// Gets or Sets DiscountLines
        /// </summary>
        [DataMember(Name = "discount_lines", EmitDefaultValue = false)]
        public OrderResponseDiscountLines DiscountLines { get; set; }

        /// <summary>
        /// Gets or Sets Charges
        /// </summary>
        [DataMember(Name = "charges", EmitDefaultValue = false)]
        public OrderResponseCharges Charges { get; set; }

        /// <summary>
        /// Partial reference information (when applicable). Structure may vary depending on the payment flow.
        /// </summary>
        /// <value>Partial reference information (when applicable). Structure may vary depending on the payment flow.</value>
        [DataMember(Name = "partial_reference", EmitDefaultValue = true)]
        public Dictionary<string, Object> PartialReference { get; set; }

        /// <summary>
        /// Additional payment information (when available). Structure may vary.
        /// </summary>
        /// <value>Additional payment information (when available). Structure may vary.</value>
        [DataMember(Name = "payments_info", EmitDefaultValue = true)]
        public Dictionary<string, Object> PaymentsInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Object: ").Append(Object).Append("\n");
            sb.Append("  Livemode: ").Append(Livemode).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  PaymentStatus: ").Append(PaymentStatus).Append("\n");
            sb.Append("  AmountRefunded: ").Append(AmountRefunded).Append("\n");
            sb.Append("  SplitPayment: ").Append(SplitPayment).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  IsRefundable: ").Append(IsRefundable).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  CustomerInfo: ").Append(CustomerInfo).Append("\n");
            sb.Append("  ShippingContact: ").Append(ShippingContact).Append("\n");
            sb.Append("  Channel: ").Append(Channel).Append("\n");
            sb.Append("  FiscalEntity: ").Append(FiscalEntity).Append("\n");
            sb.Append("  Checkout: ").Append(Checkout).Append("\n");
            sb.Append("  LineItems: ").Append(LineItems).Append("\n");
            sb.Append("  DiscountLines: ").Append(DiscountLines).Append("\n");
            sb.Append("  Charges: ").Append(Charges).Append("\n");
            sb.Append("  PartialReference: ").Append(PartialReference).Append("\n");
            sb.Append("  PaymentsInfo: ").Append(PaymentsInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Currency (string) maxLength
            if (this.Currency != null && this.Currency.Length > 3)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Currency, length must be less than 3.", new [] { "Currency" });
            }

            yield break;
        }
    }

}
