/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = DigitalFemsa.net.Client.OpenAPIDateConverter;

namespace DigitalFemsa.net.Model
{
    /// <summary>
    /// Request body to update a customer.
    /// </summary>
    [DataContract(Name = "update_customer")]
    public partial class UpdateCustomer : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCustomer" /> class.
        /// </summary>
        /// <param name="name">Customer&#39;s name..</param>
        /// <param name="email">Customer email address..</param>
        /// <param name="phone">Customer phone number..</param>
        /// <param name="corporate">True if the customer represents a company..</param>
        /// <param name="customReference">Merchant-defined reference used to identify the customer in your system..</param>
        /// <param name="metadata">Arbitrary metadata associated with the customer..</param>
        /// <param name="paymentSources">Customer payment sources to create/attach (offline recurrent references)..</param>
        /// <param name="defaultPaymentSourceId">Sets the default payment source for the customer (must be an existing payment source on the customer)..</param>
        /// <param name="defaultFiscalEntityId">Sets the default fiscal entity for the customer (must be an existing fiscal entity on the customer)..</param>
        /// <param name="defaultShippingContactId">Sets the default shipping contact for the customer (must be an existing shipping contact on the customer)..</param>
        public UpdateCustomer(string name = default(string), string email = default(string), string phone = default(string), bool corporate = default(bool), string customReference = default(string), Dictionary<string, Object> metadata = default(Dictionary<string, Object>), List<CustomerPaymentMethodsRequest> paymentSources = default(List<CustomerPaymentMethodsRequest>), string defaultPaymentSourceId = default(string), string defaultFiscalEntityId = default(string), string defaultShippingContactId = default(string))
        {
            this.Name = name;
            this.Email = email;
            this.Phone = phone;
            this.Corporate = corporate;
            this.CustomReference = customReference;
            this.Metadata = metadata;
            this.PaymentSources = paymentSources;
            this.DefaultPaymentSourceId = defaultPaymentSourceId;
            this.DefaultFiscalEntityId = defaultFiscalEntityId;
            this.DefaultShippingContactId = defaultShippingContactId;
        }

        /// <summary>
        /// Customer&#39;s name.
        /// </summary>
        /// <value>Customer&#39;s name.</value>
        /// <example>Miguel</example>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Customer email address.
        /// </summary>
        /// <value>Customer email address.</value>
        /// <example>miguel@gmail.com</example>
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email { get; set; }

        /// <summary>
        /// Customer phone number.
        /// </summary>
        /// <value>Customer phone number.</value>
        /// <example>5215555555555</example>
        [DataMember(Name = "phone", EmitDefaultValue = false)]
        public string Phone { get; set; }

        /// <summary>
        /// True if the customer represents a company.
        /// </summary>
        /// <value>True if the customer represents a company.</value>
        [DataMember(Name = "corporate", EmitDefaultValue = true)]
        public bool Corporate { get; set; }

        /// <summary>
        /// Merchant-defined reference used to identify the customer in your system.
        /// </summary>
        /// <value>Merchant-defined reference used to identify the customer in your system.</value>
        /// <example>customer_123</example>
        [DataMember(Name = "custom_reference", EmitDefaultValue = false)]
        public string CustomReference { get; set; }

        /// <summary>
        /// Arbitrary metadata associated with the customer.
        /// </summary>
        /// <value>Arbitrary metadata associated with the customer.</value>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Customer payment sources to create/attach (offline recurrent references).
        /// </summary>
        /// <value>Customer payment sources to create/attach (offline recurrent references).</value>
        [DataMember(Name = "payment_sources", EmitDefaultValue = false)]
        public List<CustomerPaymentMethodsRequest> PaymentSources { get; set; }

        /// <summary>
        /// Sets the default payment source for the customer (must be an existing payment source on the customer).
        /// </summary>
        /// <value>Sets the default payment source for the customer (must be an existing payment source on the customer).</value>
        [DataMember(Name = "default_payment_source_id", EmitDefaultValue = false)]
        public string DefaultPaymentSourceId { get; set; }

        /// <summary>
        /// Sets the default fiscal entity for the customer (must be an existing fiscal entity on the customer).
        /// </summary>
        /// <value>Sets the default fiscal entity for the customer (must be an existing fiscal entity on the customer).</value>
        [DataMember(Name = "default_fiscal_entity_id", EmitDefaultValue = false)]
        public string DefaultFiscalEntityId { get; set; }

        /// <summary>
        /// Sets the default shipping contact for the customer (must be an existing shipping contact on the customer).
        /// </summary>
        /// <value>Sets the default shipping contact for the customer (must be an existing shipping contact on the customer).</value>
        [DataMember(Name = "default_shipping_contact_id", EmitDefaultValue = false)]
        public string DefaultShippingContactId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateCustomer {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Corporate: ").Append(Corporate).Append("\n");
            sb.Append("  CustomReference: ").Append(CustomReference).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  PaymentSources: ").Append(PaymentSources).Append("\n");
            sb.Append("  DefaultPaymentSourceId: ").Append(DefaultPaymentSourceId).Append("\n");
            sb.Append("  DefaultFiscalEntityId: ").Append(DefaultFiscalEntityId).Append("\n");
            sb.Append("  DefaultShippingContactId: ").Append(DefaultShippingContactId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
