/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing ApiKeyUpdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiKeyUpdateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiKeyUpdateRequest
        //private ApiKeyUpdateRequest instance;

        public ApiKeyUpdateRequestTests()
        {
            // TODO uncomment below to create an instance of ApiKeyUpdateRequest
            //instance = new ApiKeyUpdateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiKeyUpdateRequest
        /// </summary>
        [Fact]
        public void ApiKeyUpdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiKeyUpdateRequest
            //Assert.IsType<ApiKeyUpdateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
