/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing BalanceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BalanceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BalanceResponse
        //private BalanceResponse instance;

        public BalanceResponseTests()
        {
            // TODO uncomment below to create an instance of BalanceResponse
            //instance = new BalanceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BalanceResponse
        /// </summary>
        [Fact]
        public void BalanceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BalanceResponse
            //Assert.IsType<BalanceResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Available'
        /// </summary>
        [Fact]
        public void AvailableTest()
        {
            // TODO unit test for the property 'Available'
        }

        /// <summary>
        /// Test the property 'CashoutRetentionAmount'
        /// </summary>
        [Fact]
        public void CashoutRetentionAmountTest()
        {
            // TODO unit test for the property 'CashoutRetentionAmount'
        }

        /// <summary>
        /// Test the property 'ConektaRetention'
        /// </summary>
        [Fact]
        public void ConektaRetentionTest()
        {
            // TODO unit test for the property 'ConektaRetention'
        }

        /// <summary>
        /// Test the property 'Gateway'
        /// </summary>
        [Fact]
        public void GatewayTest()
        {
            // TODO unit test for the property 'Gateway'
        }

        /// <summary>
        /// Test the property 'Pending'
        /// </summary>
        [Fact]
        public void PendingTest()
        {
            // TODO unit test for the property 'Pending'
        }

        /// <summary>
        /// Test the property 'Retained'
        /// </summary>
        [Fact]
        public void RetainedTest()
        {
            // TODO unit test for the property 'Retained'
        }

        /// <summary>
        /// Test the property 'RetentionAmount'
        /// </summary>
        [Fact]
        public void RetentionAmountTest()
        {
            // TODO unit test for the property 'RetentionAmount'
        }

        /// <summary>
        /// Test the property 'TargetCollateralAmount'
        /// </summary>
        [Fact]
        public void TargetCollateralAmountTest()
        {
            // TODO unit test for the property 'TargetCollateralAmount'
        }

        /// <summary>
        /// Test the property 'TargetRetentionAmount'
        /// </summary>
        [Fact]
        public void TargetRetentionAmountTest()
        {
            // TODO unit test for the property 'TargetRetentionAmount'
        }

        /// <summary>
        /// Test the property 'TemporarilyRetained'
        /// </summary>
        [Fact]
        public void TemporarilyRetainedTest()
        {
            // TODO unit test for the property 'TemporarilyRetained'
        }
    }
}
