/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing ChargeUpdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChargeUpdateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChargeUpdateRequest
        //private ChargeUpdateRequest instance;

        public ChargeUpdateRequestTests()
        {
            // TODO uncomment below to create an instance of ChargeUpdateRequest
            //instance = new ChargeUpdateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChargeUpdateRequest
        /// </summary>
        [Fact]
        public void ChargeUpdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChargeUpdateRequest
            //Assert.IsType<ChargeUpdateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ReferenceId'
        /// </summary>
        [Fact]
        public void ReferenceIdTest()
        {
            // TODO unit test for the property 'ReferenceId'
        }
    }
}
