/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing ChargeOrderResponseChannel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChargeOrderResponseChannelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChargeOrderResponseChannel
        //private ChargeOrderResponseChannel instance;

        public ChargeOrderResponseChannelTests()
        {
            // TODO uncomment below to create an instance of ChargeOrderResponseChannel
            //instance = new ChargeOrderResponseChannel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChargeOrderResponseChannel
        /// </summary>
        [Fact]
        public void ChargeOrderResponseChannelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChargeOrderResponseChannel
            //Assert.IsType<ChargeOrderResponseChannel>(instance);
        }

        /// <summary>
        /// Test the property 'Segment'
        /// </summary>
        [Fact]
        public void SegmentTest()
        {
            // TODO unit test for the property 'Segment'
        }

        /// <summary>
        /// Test the property 'CheckoutRequestId'
        /// </summary>
        [Fact]
        public void CheckoutRequestIdTest()
        {
            // TODO unit test for the property 'CheckoutRequestId'
        }

        /// <summary>
        /// Test the property 'CheckoutRequestType'
        /// </summary>
        [Fact]
        public void CheckoutRequestTypeTest()
        {
            // TODO unit test for the property 'CheckoutRequestType'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
