/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing CheckoutRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckoutRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckoutRequest
        //private CheckoutRequest instance;

        public CheckoutRequestTests()
        {
            // TODO uncomment below to create an instance of CheckoutRequest
            //instance = new CheckoutRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckoutRequest
        /// </summary>
        [Fact]
        public void CheckoutRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckoutRequest
            //Assert.IsType<CheckoutRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AllowedPaymentMethods'
        /// </summary>
        [Fact]
        public void AllowedPaymentMethodsTest()
        {
            // TODO unit test for the property 'AllowedPaymentMethods'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

        /// <summary>
        /// Test the property 'FailureUrl'
        /// </summary>
        [Fact]
        public void FailureUrlTest()
        {
            // TODO unit test for the property 'FailureUrl'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'OnDemandEnabled'
        /// </summary>
        [Fact]
        public void OnDemandEnabledTest()
        {
            // TODO unit test for the property 'OnDemandEnabled'
        }

        /// <summary>
        /// Test the property 'SuccessUrl'
        /// </summary>
        [Fact]
        public void SuccessUrlTest()
        {
            // TODO unit test for the property 'SuccessUrl'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
