/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing Checkout
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckoutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Checkout
        //private Checkout instance;

        public CheckoutTests()
        {
            // TODO uncomment below to create an instance of Checkout
            //instance = new Checkout();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Checkout
        /// </summary>
        [Fact]
        public void CheckoutInstanceTest()
        {
            // TODO uncomment below to test "IsType" Checkout
            //Assert.IsType<Checkout>(instance);
        }

        /// <summary>
        /// Test the property 'AllowedPaymentMethods'
        /// </summary>
        [Fact]
        public void AllowedPaymentMethodsTest()
        {
            // TODO unit test for the property 'AllowedPaymentMethods'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'NeedsShippingContact'
        /// </summary>
        [Fact]
        public void NeedsShippingContactTest()
        {
            // TODO unit test for the property 'NeedsShippingContact'
        }

        /// <summary>
        /// Test the property 'OnDemandEnabled'
        /// </summary>
        [Fact]
        public void OnDemandEnabledTest()
        {
            // TODO unit test for the property 'OnDemandEnabled'
        }

        /// <summary>
        /// Test the property 'OrderTemplate'
        /// </summary>
        [Fact]
        public void OrderTemplateTest()
        {
            // TODO unit test for the property 'OrderTemplate'
        }

        /// <summary>
        /// Test the property 'PaymentsLimitCount'
        /// </summary>
        [Fact]
        public void PaymentsLimitCountTest()
        {
            // TODO unit test for the property 'PaymentsLimitCount'
        }

        /// <summary>
        /// Test the property 'Recurrent'
        /// </summary>
        [Fact]
        public void RecurrentTest()
        {
            // TODO unit test for the property 'Recurrent'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
