/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing CompanyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompanyResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompanyResponse
        //private CompanyResponse instance;

        public CompanyResponseTests()
        {
            // TODO uncomment below to create an instance of CompanyResponse
            //instance = new CompanyResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompanyResponse
        /// </summary>
        [Fact]
        public void CompanyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompanyResponse
            //Assert.IsType<CompanyResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'ParentCompanyId'
        /// </summary>
        [Fact]
        public void ParentCompanyIdTest()
        {
            // TODO unit test for the property 'ParentCompanyId'
        }

        /// <summary>
        /// Test the property 'UseParentFiscalData'
        /// </summary>
        [Fact]
        public void UseParentFiscalDataTest()
        {
            // TODO unit test for the property 'UseParentFiscalData'
        }

        /// <summary>
        /// Test the property 'PayoutDestination'
        /// </summary>
        [Fact]
        public void PayoutDestinationTest()
        {
            // TODO unit test for the property 'PayoutDestination'
        }

        /// <summary>
        /// Test the property 'FiscalInfo'
        /// </summary>
        [Fact]
        public void FiscalInfoTest()
        {
            // TODO unit test for the property 'FiscalInfo'
        }
    }
}
