/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing CompanyPayoutDestinationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompanyPayoutDestinationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompanyPayoutDestinationResponse
        //private CompanyPayoutDestinationResponse instance;

        public CompanyPayoutDestinationResponseTests()
        {
            // TODO uncomment below to create an instance of CompanyPayoutDestinationResponse
            //instance = new CompanyPayoutDestinationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompanyPayoutDestinationResponse
        /// </summary>
        [Fact]
        public void CompanyPayoutDestinationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompanyPayoutDestinationResponse
            //Assert.IsType<CompanyPayoutDestinationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'AccountHolderName'
        /// </summary>
        [Fact]
        public void AccountHolderNameTest()
        {
            // TODO unit test for the property 'AccountHolderName'
        }

        /// <summary>
        /// Test the property 'Bank'
        /// </summary>
        [Fact]
        public void BankTest()
        {
            // TODO unit test for the property 'Bank'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Fact]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
    }
}
