/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing CompanyFiscalInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CompanyFiscalInfoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CompanyFiscalInfoResponse
        //private CompanyFiscalInfoResponse instance;

        public CompanyFiscalInfoResponseTests()
        {
            // TODO uncomment below to create an instance of CompanyFiscalInfoResponse
            //instance = new CompanyFiscalInfoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CompanyFiscalInfoResponse
        /// </summary>
        [Fact]
        public void CompanyFiscalInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CompanyFiscalInfoResponse
            //Assert.IsType<CompanyFiscalInfoResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'TaxId'
        /// </summary>
        [Fact]
        public void TaxIdTest()
        {
            // TODO unit test for the property 'TaxId'
        }

        /// <summary>
        /// Test the property 'LegalEntityName'
        /// </summary>
        [Fact]
        public void LegalEntityNameTest()
        {
            // TODO unit test for the property 'LegalEntityName'
        }

        /// <summary>
        /// Test the property 'BusinessType'
        /// </summary>
        [Fact]
        public void BusinessTypeTest()
        {
            // TODO unit test for the property 'BusinessType'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'PhysicalPersonBusinessType'
        /// </summary>
        [Fact]
        public void PhysicalPersonBusinessTypeTest()
        {
            // TODO unit test for the property 'PhysicalPersonBusinessType'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
    }
}
