/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing CreateCustomerPaymentMethodsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCustomerPaymentMethodsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateCustomerPaymentMethodsRequest
        //private CreateCustomerPaymentMethodsRequest instance;

        public CreateCustomerPaymentMethodsRequestTests()
        {
            // TODO uncomment below to create an instance of CreateCustomerPaymentMethodsRequest
            //instance = new CreateCustomerPaymentMethodsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateCustomerPaymentMethodsRequest
        /// </summary>
        [Fact]
        public void CreateCustomerPaymentMethodsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateCustomerPaymentMethodsRequest
            //Assert.IsType<CreateCustomerPaymentMethodsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }
    }
}
