/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerShippingContactsResponseAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerShippingContactsResponseAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerShippingContactsResponseAddress
        //private CustomerShippingContactsResponseAddress instance;

        public CustomerShippingContactsResponseAddressTests()
        {
            // TODO uncomment below to create an instance of CustomerShippingContactsResponseAddress
            //instance = new CustomerShippingContactsResponseAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerShippingContactsResponseAddress
        /// </summary>
        [Fact]
        public void CustomerShippingContactsResponseAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerShippingContactsResponseAddress
            //Assert.IsType<CustomerShippingContactsResponseAddress>(instance);
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'Street1'
        /// </summary>
        [Fact]
        public void Street1Test()
        {
            // TODO unit test for the property 'Street1'
        }

        /// <summary>
        /// Test the property 'Street2'
        /// </summary>
        [Fact]
        public void Street2Test()
        {
            // TODO unit test for the property 'Street2'
        }

        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Residential'
        /// </summary>
        [Fact]
        public void ResidentialTest()
        {
            // TODO unit test for the property 'Residential'
        }
    }
}
