/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerFiscalEntitiesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerFiscalEntitiesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerFiscalEntitiesResponse
        //private CustomerFiscalEntitiesResponse instance;

        public CustomerFiscalEntitiesResponseTests()
        {
            // TODO uncomment below to create an instance of CustomerFiscalEntitiesResponse
            //instance = new CustomerFiscalEntitiesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerFiscalEntitiesResponse
        /// </summary>
        [Fact]
        public void CustomerFiscalEntitiesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerFiscalEntitiesResponse
            //Assert.IsType<CustomerFiscalEntitiesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'HasMore'
        /// </summary>
        [Fact]
        public void HasMoreTest()
        {
            // TODO unit test for the property 'HasMore'
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
