/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerUpdateFiscalEntitiesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerUpdateFiscalEntitiesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerUpdateFiscalEntitiesRequest
        //private CustomerUpdateFiscalEntitiesRequest instance;

        public CustomerUpdateFiscalEntitiesRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerUpdateFiscalEntitiesRequest
            //instance = new CustomerUpdateFiscalEntitiesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerUpdateFiscalEntitiesRequest
        /// </summary>
        [Fact]
        public void CustomerUpdateFiscalEntitiesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerUpdateFiscalEntitiesRequest
            //Assert.IsType<CustomerUpdateFiscalEntitiesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'TaxId'
        /// </summary>
        [Fact]
        public void TaxIdTest()
        {
            // TODO unit test for the property 'TaxId'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
    }
}
