/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerInfoJustCustomerIdResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerInfoJustCustomerIdResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerInfoJustCustomerIdResponse
        //private CustomerInfoJustCustomerIdResponse instance;

        public CustomerInfoJustCustomerIdResponseTests()
        {
            // TODO uncomment below to create an instance of CustomerInfoJustCustomerIdResponse
            //instance = new CustomerInfoJustCustomerIdResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerInfoJustCustomerIdResponse
        /// </summary>
        [Fact]
        public void CustomerInfoJustCustomerIdResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerInfoJustCustomerIdResponse
            //Assert.IsType<CustomerInfoJustCustomerIdResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
    }
}
