/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerPaymentMethodRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerPaymentMethodRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerPaymentMethodRequest
        //private CustomerPaymentMethodRequest instance;

        public CustomerPaymentMethodRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerPaymentMethodRequest
            //instance = new CustomerPaymentMethodRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerPaymentMethodRequest
        /// </summary>
        [Fact]
        public void CustomerPaymentMethodRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerPaymentMethodRequest
            //Assert.IsType<CustomerPaymentMethodRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
