/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing Details
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Details
        //private Details instance;

        public DetailsTests()
        {
            // TODO uncomment below to create an instance of Details
            //instance = new Details();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Details
        /// </summary>
        [Fact]
        public void DetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Details
            //Assert.IsType<Details>(instance);
        }

        /// <summary>
        /// Test the property 'VarDetails'
        /// </summary>
        [Fact]
        public void VarDetailsTest()
        {
            // TODO unit test for the property 'VarDetails'
        }
    }
}
