/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing DetailsError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetailsErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DetailsError
        //private DetailsError instance;

        public DetailsErrorTests()
        {
            // TODO uncomment below to create an instance of DetailsError
            //instance = new DetailsError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DetailsError
        /// </summary>
        [Fact]
        public void DetailsErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" DetailsError
            //Assert.IsType<DetailsError>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Param'
        /// </summary>
        [Fact]
        public void ParamTest()
        {
            // TODO unit test for the property 'Param'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'DebugMessage'
        /// </summary>
        [Fact]
        public void DebugMessageTest()
        {
            // TODO unit test for the property 'DebugMessage'
        }
    }
}
