/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing EmailCheckoutRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailCheckoutRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailCheckoutRequest
        //private EmailCheckoutRequest instance;

        public EmailCheckoutRequestTests()
        {
            // TODO uncomment below to create an instance of EmailCheckoutRequest
            //instance = new EmailCheckoutRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailCheckoutRequest
        /// </summary>
        [Fact]
        public void EmailCheckoutRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailCheckoutRequest
            //Assert.IsType<EmailCheckoutRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
