/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing EventResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventResponse
        //private EventResponse instance;

        public EventResponseTests()
        {
            // TODO uncomment below to create an instance of EventResponse
            //instance = new EventResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventResponse
        /// </summary>
        [Fact]
        public void EventResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventResponse
            //Assert.IsType<EventResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Livemode'
        /// </summary>
        [Fact]
        public void LivemodeTest()
        {
            // TODO unit test for the property 'Livemode'
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'WebhookLogs'
        /// </summary>
        [Fact]
        public void WebhookLogsTest()
        {
            // TODO unit test for the property 'WebhookLogs'
        }

        /// <summary>
        /// Test the property 'WebhookStatus'
        /// </summary>
        [Fact]
        public void WebhookStatusTest()
        {
            // TODO unit test for the property 'WebhookStatus'
        }
    }
}
