/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing EventsResendResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventsResendResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventsResendResponse
        //private EventsResendResponse instance;

        public EventsResendResponseTests()
        {
            // TODO uncomment below to create an instance of EventsResendResponse
            //instance = new EventsResendResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventsResendResponse
        /// </summary>
        [Fact]
        public void EventsResendResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" EventsResendResponse
            //Assert.IsType<EventsResendResponse>(instance);
        }

        /// <summary>
        /// Test the property 'FailedAttempts'
        /// </summary>
        [Fact]
        public void FailedAttemptsTest()
        {
            // TODO unit test for the property 'FailedAttempts'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'LastAttemptedAt'
        /// </summary>
        [Fact]
        public void LastAttemptedAtTest()
        {
            // TODO unit test for the property 'LastAttemptedAt'
        }

        /// <summary>
        /// Test the property 'LastHttpResponseStatus'
        /// </summary>
        [Fact]
        public void LastHttpResponseStatusTest()
        {
            // TODO unit test for the property 'LastHttpResponseStatus'
        }

        /// <summary>
        /// Test the property 'ResponseData'
        /// </summary>
        [Fact]
        public void ResponseDataTest()
        {
            // TODO unit test for the property 'ResponseData'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
