/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing OrderResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderResponse
        //private OrderResponse instance;

        public OrderResponseTests()
        {
            // TODO uncomment below to create an instance of OrderResponse
            //instance = new OrderResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderResponse
        /// </summary>
        [Fact]
        public void OrderResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderResponse
            //Assert.IsType<OrderResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'AmountRefunded'
        /// </summary>
        [Fact]
        public void AmountRefundedTest()
        {
            // TODO unit test for the property 'AmountRefunded'
        }

        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Fact]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }

        /// <summary>
        /// Test the property 'Charges'
        /// </summary>
        [Fact]
        public void ChargesTest()
        {
            // TODO unit test for the property 'Charges'
        }

        /// <summary>
        /// Test the property 'Checkout'
        /// </summary>
        [Fact]
        public void CheckoutTest()
        {
            // TODO unit test for the property 'Checkout'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'CustomerInfo'
        /// </summary>
        [Fact]
        public void CustomerInfoTest()
        {
            // TODO unit test for the property 'CustomerInfo'
        }

        /// <summary>
        /// Test the property 'DiscountLines'
        /// </summary>
        [Fact]
        public void DiscountLinesTest()
        {
            // TODO unit test for the property 'DiscountLines'
        }

        /// <summary>
        /// Test the property 'FiscalEntity'
        /// </summary>
        [Fact]
        public void FiscalEntityTest()
        {
            // TODO unit test for the property 'FiscalEntity'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IsRefundable'
        /// </summary>
        [Fact]
        public void IsRefundableTest()
        {
            // TODO unit test for the property 'IsRefundable'
        }

        /// <summary>
        /// Test the property 'LineItems'
        /// </summary>
        [Fact]
        public void LineItemsTest()
        {
            // TODO unit test for the property 'LineItems'
        }

        /// <summary>
        /// Test the property 'Livemode'
        /// </summary>
        [Fact]
        public void LivemodeTest()
        {
            // TODO unit test for the property 'Livemode'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'NextAction'
        /// </summary>
        [Fact]
        public void NextActionTest()
        {
            // TODO unit test for the property 'NextAction'
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'PaymentStatus'
        /// </summary>
        [Fact]
        public void PaymentStatusTest()
        {
            // TODO unit test for the property 'PaymentStatus'
        }

        /// <summary>
        /// Test the property 'ProcessingMode'
        /// </summary>
        [Fact]
        public void ProcessingModeTest()
        {
            // TODO unit test for the property 'ProcessingMode'
        }

        /// <summary>
        /// Test the property 'ShippingContact'
        /// </summary>
        [Fact]
        public void ShippingContactTest()
        {
            // TODO unit test for the property 'ShippingContact'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
