/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCustomerInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCustomerInfoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCustomerInfoResponse
        //private OrderCustomerInfoResponse instance;

        public OrderCustomerInfoResponseTests()
        {
            // TODO uncomment below to create an instance of OrderCustomerInfoResponse
            //instance = new OrderCustomerInfoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCustomerInfoResponse
        /// </summary>
        [Fact]
        public void OrderCustomerInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCustomerInfoResponse
            //Assert.IsType<OrderCustomerInfoResponse>(instance);
        }

        /// <summary>
        /// Test the property 'CustomerCustomReference'
        /// </summary>
        [Fact]
        public void CustomerCustomReferenceTest()
        {
            // TODO unit test for the property 'CustomerCustomReference'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Corporate'
        /// </summary>
        [Fact]
        public void CorporateTest()
        {
            // TODO unit test for the property 'Corporate'
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
    }
}
