/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCaptureRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCaptureRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCaptureRequest
        //private OrderCaptureRequest instance;

        public OrderCaptureRequestTests()
        {
            // TODO uncomment below to create an instance of OrderCaptureRequest
            //instance = new OrderCaptureRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCaptureRequest
        /// </summary>
        [Fact]
        public void OrderCaptureRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCaptureRequest
            //Assert.IsType<OrderCaptureRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
    }
}
