/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing OrderResponseCheckout
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderResponseCheckoutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderResponseCheckout
        //private OrderResponseCheckout instance;

        public OrderResponseCheckoutTests()
        {
            // TODO uncomment below to create an instance of OrderResponseCheckout
            //instance = new OrderResponseCheckout();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderResponseCheckout
        /// </summary>
        [Fact]
        public void OrderResponseCheckoutInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderResponseCheckout
            //Assert.IsType<OrderResponseCheckout>(instance);
        }

        /// <summary>
        /// Test the property 'AllowedPaymentMethods'
        /// </summary>
        [Fact]
        public void AllowedPaymentMethodsTest()
        {
            // TODO unit test for the property 'AllowedPaymentMethods'
        }

        /// <summary>
        /// Test the property 'CanNotExpire'
        /// </summary>
        [Fact]
        public void CanNotExpireTest()
        {
            // TODO unit test for the property 'CanNotExpire'
        }

        /// <summary>
        /// Test the property 'EmailsSent'
        /// </summary>
        [Fact]
        public void EmailsSentTest()
        {
            // TODO unit test for the property 'EmailsSent'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }

        /// <summary>
        /// Test the property 'FailureUrl'
        /// </summary>
        [Fact]
        public void FailureUrlTest()
        {
            // TODO unit test for the property 'FailureUrl'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IsRedirectOnFailure'
        /// </summary>
        [Fact]
        public void IsRedirectOnFailureTest()
        {
            // TODO unit test for the property 'IsRedirectOnFailure'
        }

        /// <summary>
        /// Test the property 'Livemode'
        /// </summary>
        [Fact]
        public void LivemodeTest()
        {
            // TODO unit test for the property 'Livemode'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'NeedsShippingContact'
        /// </summary>
        [Fact]
        public void NeedsShippingContactTest()
        {
            // TODO unit test for the property 'NeedsShippingContact'
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'OnDemandEnabled'
        /// </summary>
        [Fact]
        public void OnDemandEnabledTest()
        {
            // TODO unit test for the property 'OnDemandEnabled'
        }

        /// <summary>
        /// Test the property 'Recurrent'
        /// </summary>
        [Fact]
        public void RecurrentTest()
        {
            // TODO unit test for the property 'Recurrent'
        }

        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Fact]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }

        /// <summary>
        /// Test the property 'SmsSent'
        /// </summary>
        [Fact]
        public void SmsSentTest()
        {
            // TODO unit test for the property 'SmsSent'
        }

        /// <summary>
        /// Test the property 'SuccessUrl'
        /// </summary>
        [Fact]
        public void SuccessUrlTest()
        {
            // TODO unit test for the property 'SuccessUrl'
        }

        /// <summary>
        /// Test the property 'StartsAt'
        /// </summary>
        [Fact]
        public void StartsAtTest()
        {
            // TODO unit test for the property 'StartsAt'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
