/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing OrderRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderRequest
        //private OrderRequest instance;

        public OrderRequestTests()
        {
            // TODO uncomment below to create an instance of OrderRequest
            //instance = new OrderRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderRequest
        /// </summary>
        [Fact]
        public void OrderRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderRequest
            //Assert.IsType<OrderRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Charges'
        /// </summary>
        [Fact]
        public void ChargesTest()
        {
            // TODO unit test for the property 'Charges'
        }

        /// <summary>
        /// Test the property 'Checkout'
        /// </summary>
        [Fact]
        public void CheckoutTest()
        {
            // TODO unit test for the property 'Checkout'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'CustomerInfo'
        /// </summary>
        [Fact]
        public void CustomerInfoTest()
        {
            // TODO unit test for the property 'CustomerInfo'
        }

        /// <summary>
        /// Test the property 'DiscountLines'
        /// </summary>
        [Fact]
        public void DiscountLinesTest()
        {
            // TODO unit test for the property 'DiscountLines'
        }

        /// <summary>
        /// Test the property 'FiscalEntity'
        /// </summary>
        [Fact]
        public void FiscalEntityTest()
        {
            // TODO unit test for the property 'FiscalEntity'
        }

        /// <summary>
        /// Test the property 'LineItems'
        /// </summary>
        [Fact]
        public void LineItemsTest()
        {
            // TODO unit test for the property 'LineItems'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'NeedsShippingContact'
        /// </summary>
        [Fact]
        public void NeedsShippingContactTest()
        {
            // TODO unit test for the property 'NeedsShippingContact'
        }

        /// <summary>
        /// Test the property 'ProcessingMode'
        /// </summary>
        [Fact]
        public void ProcessingModeTest()
        {
            // TODO unit test for the property 'ProcessingMode'
        }

        /// <summary>
        /// Test the property 'ReturnUrl'
        /// </summary>
        [Fact]
        public void ReturnUrlTest()
        {
            // TODO unit test for the property 'ReturnUrl'
        }

        /// <summary>
        /// Test the property 'ShippingContact'
        /// </summary>
        [Fact]
        public void ShippingContactTest()
        {
            // TODO unit test for the property 'ShippingContact'
        }

        /// <summary>
        /// Test the property 'ShippingLines'
        /// </summary>
        [Fact]
        public void ShippingLinesTest()
        {
            // TODO unit test for the property 'ShippingLines'
        }

        /// <summary>
        /// Test the property 'TaxLines'
        /// </summary>
        [Fact]
        public void TaxLinesTest()
        {
            // TODO unit test for the property 'TaxLines'
        }
    }
}
