/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateOrderDiscountLinesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateOrderDiscountLinesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateOrderDiscountLinesRequest
        //private UpdateOrderDiscountLinesRequest instance;

        public UpdateOrderDiscountLinesRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateOrderDiscountLinesRequest
            //instance = new UpdateOrderDiscountLinesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateOrderDiscountLinesRequest
        /// </summary>
        [Fact]
        public void UpdateOrderDiscountLinesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateOrderDiscountLinesRequest
            //Assert.IsType<UpdateOrderDiscountLinesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
