/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateCustomerAntifraudInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateCustomerAntifraudInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateCustomerAntifraudInfo
        //private UpdateCustomerAntifraudInfo instance;

        public UpdateCustomerAntifraudInfoTests()
        {
            // TODO uncomment below to create an instance of UpdateCustomerAntifraudInfo
            //instance = new UpdateCustomerAntifraudInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateCustomerAntifraudInfo
        /// </summary>
        [Fact]
        public void UpdateCustomerAntifraudInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateCustomerAntifraudInfo
            //Assert.IsType<UpdateCustomerAntifraudInfo>(instance);
        }

        /// <summary>
        /// Test the property 'AccountCreatedAt'
        /// </summary>
        [Fact]
        public void AccountCreatedAtTest()
        {
            // TODO unit test for the property 'AccountCreatedAt'
        }

        /// <summary>
        /// Test the property 'FirstPaidAt'
        /// </summary>
        [Fact]
        public void FirstPaidAtTest()
        {
            // TODO unit test for the property 'FirstPaidAt'
        }
    }
}
