/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing UpdatePaymentMethods
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdatePaymentMethodsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdatePaymentMethods
        //private UpdatePaymentMethods instance;

        public UpdatePaymentMethodsTests()
        {
            // TODO uncomment below to create an instance of UpdatePaymentMethods
            //instance = new UpdatePaymentMethods();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdatePaymentMethods
        /// </summary>
        [Fact]
        public void UpdatePaymentMethodsInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdatePaymentMethods
            //Assert.IsType<UpdatePaymentMethods>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
