/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateCustomer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateCustomerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateCustomer
        //private UpdateCustomer instance;

        public UpdateCustomerTests()
        {
            // TODO uncomment below to create an instance of UpdateCustomer
            //instance = new UpdateCustomer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateCustomer
        /// </summary>
        [Fact]
        public void UpdateCustomerInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateCustomer
            //Assert.IsType<UpdateCustomer>(instance);
        }

        /// <summary>
        /// Test the property 'AntifraudInfo'
        /// </summary>
        [Fact]
        public void AntifraudInfoTest()
        {
            // TODO unit test for the property 'AntifraudInfo'
        }

        /// <summary>
        /// Test the property 'DefaultPaymentSourceId'
        /// </summary>
        [Fact]
        public void DefaultPaymentSourceIdTest()
        {
            // TODO unit test for the property 'DefaultPaymentSourceId'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'DefaultShippingContactId'
        /// </summary>
        [Fact]
        public void DefaultShippingContactIdTest()
        {
            // TODO unit test for the property 'DefaultShippingContactId'
        }

        /// <summary>
        /// Test the property 'Corporate'
        /// </summary>
        [Fact]
        public void CorporateTest()
        {
            // TODO unit test for the property 'Corporate'
        }

        /// <summary>
        /// Test the property 'CustomReference'
        /// </summary>
        [Fact]
        public void CustomReferenceTest()
        {
            // TODO unit test for the property 'CustomReference'
        }

        /// <summary>
        /// Test the property 'FiscalEntities'
        /// </summary>
        [Fact]
        public void FiscalEntitiesTest()
        {
            // TODO unit test for the property 'FiscalEntities'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'PaymentSources'
        /// </summary>
        [Fact]
        public void PaymentSourcesTest()
        {
            // TODO unit test for the property 'PaymentSources'
        }

        /// <summary>
        /// Test the property 'ShippingContacts'
        /// </summary>
        [Fact]
        public void ShippingContactsTest()
        {
            // TODO unit test for the property 'ShippingContacts'
        }
    }
}
