/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookKeyDeleteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookKeyDeleteResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookKeyDeleteResponse
        //private WebhookKeyDeleteResponse instance;

        public WebhookKeyDeleteResponseTests()
        {
            // TODO uncomment below to create an instance of WebhookKeyDeleteResponse
            //instance = new WebhookKeyDeleteResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookKeyDeleteResponse
        /// </summary>
        [Fact]
        public void WebhookKeyDeleteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookKeyDeleteResponse
            //Assert.IsType<WebhookKeyDeleteResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Livemode'
        /// </summary>
        [Fact]
        public void LivemodeTest()
        {
            // TODO unit test for the property 'Livemode'
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }
    }
}
