/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookResponse
        //private WebhookResponse instance;

        public WebhookResponseTests()
        {
            // TODO uncomment below to create an instance of WebhookResponse
            //instance = new WebhookResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookResponse
        /// </summary>
        [Fact]
        public void WebhookResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookResponse
            //Assert.IsType<WebhookResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }

        /// <summary>
        /// Test the property 'DevelopmentEnabled'
        /// </summary>
        [Fact]
        public void DevelopmentEnabledTest()
        {
            // TODO unit test for the property 'DevelopmentEnabled'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Livemode'
        /// </summary>
        [Fact]
        public void LivemodeTest()
        {
            // TODO unit test for the property 'Livemode'
        }

        /// <summary>
        /// Test the property 'Object'
        /// </summary>
        [Fact]
        public void ObjectTest()
        {
            // TODO unit test for the property 'Object'
        }

        /// <summary>
        /// Test the property 'ProductionEnabled'
        /// </summary>
        [Fact]
        public void ProductionEnabledTest()
        {
            // TODO unit test for the property 'ProductionEnabled'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'SubscribedEvents'
        /// </summary>
        [Fact]
        public void SubscribedEventsTest()
        {
            // TODO unit test for the property 'SubscribedEvents'
        }

        /// <summary>
        /// Test the property 'Synchronous'
        /// </summary>
        [Fact]
        public void SynchronousTest()
        {
            // TODO unit test for the property 'Synchronous'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
