/*
 * Femsa API
 *
 * Femsa sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@femsa.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using DigitalFemsa.net.Model;
using DigitalFemsa.net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace DigitalFemsa.net.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookRequest
        //private WebhookRequest instance;

        public WebhookRequestTests()
        {
            // TODO uncomment below to create an instance of WebhookRequest
            //instance = new WebhookRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookRequest
        /// </summary>
        [Fact]
        public void WebhookRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookRequest
            //Assert.IsType<WebhookRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Synchronous'
        /// </summary>
        [Fact]
        public void SynchronousTest()
        {
            // TODO unit test for the property 'Synchronous'
        }
    }
}
